### ISSUE TITLE
I have got an empty image with pngpaste in OSX 10.12

### ISSUE THREAD

**Issue by griffinqiu** [jcsalterego/pngpaste#11]
I installed pngpaste via brew.
However, the pngpaste does not work as well.
An empty image been generate like:

![image](https://cloud.githubusercontent.com/assets/179343/24322039/e9616b04-1196-11e7-8288-b06705b012d0.png)

**Comment by griffinqiu** [comment]
It works if I copied more than one png files.
However, I will get an empty file if I only copy one png file

**Comment by jcsalterego** [comment]
@griffinqiu Oh no, that doesn't sound great. However, I haven't been able to reproduce this. How are you copying the PNG file in the first place?

**Comment by griffinqiu** [comment]
I copied that png file with command-c

**Comment by jcsalterego** [comment]
In Preview, or in Finder?

**Comment by griffinqiu** [comment]
in Finder. However, it could be paste one file if I copy two files in Finder

**Comment by jcsalterego** [comment]
OK, I have been able to reproduce this locally with another destination application:

1. Copy one PNG in Finder (highlight and Edit > Copy "file.png")
2. Paste in Photoshop

Result: 1024x1024 PNG that represents the file type.

I don't think Finder actually makes the image data available, but provides a reference to the original file. Looking at the output of `pbpaste`, it is the filename, not the contents of the file.

Ultimately I don't think Finder Copy is a supported source for pngpaste, and it only supports copying an image directly, rather than copying a reference to a file.

**Comment by griffinqiu** [comment]
Thanks, I got it
